### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by tommykennedy** [mjpearson/passport-slack#1]
I was wondering why this module requires authentication every time I use it to log in, even if I am logged into slack.

Facebook passes the request straight thru.

Any ideas?

**Comment by mjpearson** [comment]
It's really up to the oAuth provider on how they handle oauth requests, facebook for example will re-prompt for authorization if oauth permission changes, but pass through silently otherwise (as you noted).  

This would be a policy of Slack themselves, rather than the passport implementation
