### ISSUE TITLE
500 MISSING_SCOPE when performing auth callback

### ISSUE THREAD

**Issue by dannypier** [mjpearson/passport-slack#10]
I implemented the example in the documentation as follows:

```
router.get('/auth',
    passport.authorize('slack'));

router.get('/auth/callback',
    passport.authorize('slack', { failureRedirect: '/login' }),
    function(req, res) {
        console.log("TEST");
        // Successful authentication, redirect home.
        res.redirect('/slack');
    });
```

I was able to successfully request permissions from slack and return the the /auth/callback endpoint. However, after that point I would receive a 500 error of "missing_scope".

My strategy looks as follows:

```
passport.use(new SlackStrategy({
    //TODO this needs to not be in the .js
        clientID: "CLIENT",
        clientSecret: "SECRET",
        scope: 'identify channels:read channels:history reactions:read'
    },
    function(accessToken, refreshToken, profile, done) {
        User.findOrCreate({ SlackId: profile.id }, function (err, user) {
            return done(err, profile);
        });
    }
));
```

I was able to track it down to the oauth2 library loading the profile on the auth callback. However, I didn't have the required scope slack needed to allow me to do that. After adding the ```users:read``` scope, I was able to successfully retrieve my access token and user.

Not sure if an internal change is required or it's merely a matter of citing that ```users:read``` is required as a scope for the access token function to work.

**Comment by olalonde** [comment]
Getting same errror "missing_scope"

**Comment by mjpearson** [comment]
I'm hesitant to add an internal change because it's not a passport clients responsibility to make decision about scope (in my opinion).  Understanding the `users:read` scope means this client needs to follow Slack API changes, and makes assumptions around scope intent.

The intent with this passport strategy is to informing the client correctly with an appropriate error condition.  Is that happening?

**Comment by olalonde** [comment]
You already made that decision by making this passport require the scope to work. At least add this to the README.

**Comment by mjpearson** [comment]
`userProfile` should return an error condition which is consistent with nearly all other passport strategies. If you don't need the scope then ignore this error.

**Comment by olalonde** [comment]
AFAIK your strategy doesn't work at all without that scope. Why make it optional if 100% of users need to use the scope to use your strategy? At least put a big note in the README?

**Comment by mjpearson** [comment]
readme has been updated via PR's :  

https://github.com/mjpearson/passport-slack/pull/11
https://github.com/mjpearson/passport-slack/pull/12

You can now pass the `skipUserProfile` flag via passport oauth options hand have it honored correctly (or warn appropriately if getting profile without scope)

**Comment by olalonde** [comment]
Good :+1:

**Comment by primeobsession** [comment]
Not suggesting this be merged in but its relevant.   When requesting `bot` permissions, the bot token actually gets access to `users:read`.  I wanted to reduce the number of permissions needed so hacked my fork to use the bot token when requesting users.info.

Sadly, the easiest way I could find to work this hack out was to override a lot of the code from the passport libs.  

Check it out here around line 124:  https://github.com/primeobsession/passport-slack/blob/master/lib/passport-slack/strategy.js
