### ISSUE TITLE
Scope changes in process flow

### ISSUE THREAD

**Issue by borzos6** [mjpearson/passport-slack#21]
Hi!

Slack introduced new scopes in the Oauth flow: identity.basic, identity.email.
https://api.slack.com/methods/users.identity
With these you don't have to allow access to all the team users (users:read), just identify yourself.
Unfortunately this library cannot handle it yet (Scope 'users:read' is required to retrieve Slack u
ser profile + returns with [Object object] instead of the user).

It would be nice to update the lib :)
Thanks

**Comment by mjpearson** [comment]
There's a PR for this, I'll publish soon https://github.com/mjpearson/passport-slack/pull/22/commits/e891e180a2746a85815cbe53066e5c6189364830

apologies for the tardy response

**Comment by mjpearson** [comment]
a fix for this has been pushed to npm as 0.0.7

**Comment by borzos6** [comment]
Thanks, you're the best :)
