### ISSUE TITLE
Support for oauth v2 endpoint

### ISSUE THREAD

**Issue by guillaumelachaud** [mjpearson/passport-slack#46]
Slack has introduced new Slack apps and are now making them the default. New granular scopes rely on a completely new oauth endpoint . Read more at https://api.slack.com/authentication/oauth-v2

Are there any plans to upgrade this passport module to the new endpoint ?

Thanks!

**Comment by maximgatilin** [comment]
As I can see from the source code, it is possible to just pass new url to the strategy https://github.com/mjpearson/passport-slack/blob/master/lib/passport-slack/strategy.js#L49

**Comment by guillaumelachaud** [comment]
Thanks for pointing it out. I guess it's the easiest path for now.

**Comment by maximgatilin** [comment]
@GuillaumeLachaud and tokenURL should be changed too. But I ended up creating my own auth server for it, because we should also pass user scope which is different from scope and plugins don't have this option.
