### ISSUE TITLE
Update passport-oauth to ^1.0.0

### ISSUE THREAD

**Issue by analog-nico** [mjpearson/passport-slack#6]
Unless this library upgrades to passport-oauth ^1.0.0 it will crash `req.logIn(...)` when the app is using the latest version of Passport. This is caused by introducing lazy session initialization in passport 0.3.0. See [the technical details](https://github.com/jaredhanson/passport/pull/399) and [Jared's explanation](https://github.com/jaredhanson/passport/issues/400#issuecomment-135162085).

Let me know if I can help.

**Comment by analog-nico** [comment]
FYI, passport@0.3.1 just got released which applies a general patch. So I removed the "Critical" in the title.

**Comment by mvaragnat** [comment]
Hello @analog-nico. I still don't see the sessions being intialized (there is no passport field in the session, and no call to login/serialize user occur). Any thoughts? I'm using 

```
"passport": "^0.3.2",
"passport-slack": "0.0.4"
```

**Comment by analog-nico** [comment]
Hi @mvaragnat seems like you are referring to an issue using passport-slack. Please open a new issue for that and give some example code so that the watchers are able to help you.

**Comment by mvaragnat** [comment]
Sure - I wrote here because the symptoms are the same as the issue you raised, but I'll do that. Thanks!

**Comment by analog-nico** [comment]
This issue is something internal which won't impact the user's code anymore.

I just started watching this repo so that I get notified when you open the new issue. I'll have a look at it.

**Comment by mvaragnat** [comment]
Actually, I moved back to the passport-oauth2 module and overrode the bits needed for Slack, so no worries. I'll open source the file later and link it here

**Comment by analog-nico** [comment]
+1

**Comment by schematical** [comment]
+1

**Comment by mvaragnat** [comment]
I was gently reminded to share the gist of the strategy, based on a modified oauth2 passport strategy

https://gist.github.com/mvaragnat/b835f089ee29e666c69a75c83df199e0

**Comment by saimeunt** [comment]
I ended up forking the repo to manually upgrade passport-oauth to 1.x.x
